default_platform(:ios)


platform :ios do
  desc "Déployer sur l'App Store"
  lane :deploy do
    match(type: "appstore")
    build_app(
      scheme: "Lumen_Christi_TV",
      export_method: "app-store"
    )
    upload_to_app_store
  end
end
